import type { NewsItem } from "../data";

export type ArchiveYear = {
  year: string;
  items: NewsItem[];
};

export const archiveNewsByYear: ArchiveYear[] = [
  {
    year: "2025",
    items: [
      { date: "2025.12", category: "Grant", title: "RCI Lab began a humanoid simulation research project with the Korea Institute of Machinery & Materials." },
      { date: "2025.12", category: "Lab", title: "RCI Lab completed a technology transfer agreement with MetaMotionX.", detail: "MPPI and RPP autonomous-navigation software for rough-terrain driving" },
      { date: "2025.11", category: "Grant", title: "RCI Lab received a Gyeonggi RISE Center research grant.", detail: "Off-road autonomous-driving software development, 2025–2026" },
      { date: "2025.11", category: "Grant", title: "RCI Lab began a Dual Steering AGV control project with T-ROBOTICS." },
      { date: "2025.11", category: "Award", title: "Prof. Sanghyun Kim received the JMST Outstanding Contribution Award." },
      { date: "2025.11", category: "Lab", title: "The Robros IGRIS-C humanoid robot arrived at RCI Lab." },
      { date: "2025.11", category: "Award", title: "Taehyun Jung received the Best Oral Presentation Award at the Undergraduate Research Festival.", detail: "ROS2-Based Dynamic Costmap Extension and Real-Time Avoidance Navigation in Radiation Environments" },
      { date: "2025.11", category: "Award", title: "RCI Lab received the Minister of Trade, Industry and Energy Award at the 2025 Industry–Academia Project Challenge." },
      { date: "2025.10", category: "Lab", title: "RCI Lab transferred RGB–LiDAR segmentation software to MetaMotionX." },
      { date: "2025.10", category: "Grant", title: "RCI Lab joined a Ministry of Trade, Industry and Energy project on a lightweight high-DOF humanoid robot hand." },
      { date: "2025.10", category: "Publication", title: "Two papers on rough-terrain navigation and high-fidelity simulation were accepted to the Transactions of the KSME A." },
      { date: "2025.09", category: "Lab", title: "The Unitree H1-2 full-size humanoid robot arrived at RCI Lab." },
      { date: "2025.09", category: "Grant", title: "RCI Lab joined KIRIA’s humanoid robot demonstration program." },
      { date: "2025.09", category: "Grant", title: "RCI Lab began a quadruped autonomous-navigation project with PonyLink." },
      { date: "2025.09", category: "Lab", title: "RCI Lab signed an autonomous-mobility research MOU with PonyLink and Inha University." },
      { date: "2025.08", category: "Service", title: "Prof. Sanghyun Kim was appointed an Associate Editor for ICRA 2026." },
      { date: "2025.08", category: "Grant", title: "RCI Lab began a mobile humanoid control project with T-ROBOTICS." },
      { date: "2025.08", category: "Lab", title: "RCI Lab celebrated its first M.S. graduates: Hakjun Kim, Joonyeol Yang, and Seunghyun Lee." },
      { date: "2025.07", category: "Grant", title: "RCI Lab began developing an LLM-based task generator for autonomous experiments with KailosLab." },
      { date: "2025.06", category: "Grant", title: "RCI Lab received a Kyung Hee University grant for RGB–LiDAR 2.5D autonomous navigation." },
      { date: "2025.06", category: "Publication", title: "CSC-MPPI was accepted to IEEE/RSJ IROS 2025.", detail: "Leesai Park, Keunwoo Jang, and Sanghyun Kim" },
      { date: "2025.06", category: "Lab", title: "RCI Lab held its spring-semester membership training event." },
      { date: "2025.05", category: "Grant", title: "RCI Lab joined the National Robot Test Field project on virtualized device verification for digital twins." },
      { date: "2025.05", category: "Grant", title: "RCI Lab joined the Global TOP Strategic Research Group for self-evolving AI humanoids." },
      { date: "2025.05", category: "Award", title: "Prof. Sanghyun Kim received a second JMST Outstanding Contribution Award." },
      { date: "2025.05", category: "Lab", title: "RCI Lab held an event to commemorate Teacher’s Day." },
      { date: "2025.04", category: "Grant", title: "Eunae Kang was selected as a principal investigator for the WISET Women in Engineering Graduate Research Team Program." },
      { date: "2025.04", category: "Grant", title: "RCI Lab began a bridge-inspection robot simulator project with KICT." },
      { date: "2025.03", category: "Lab", title: "Prof. Sanghyun Kim was featured by iRobotNews as a young robotics engineer." },
      { date: "2025.03", category: "Grant", title: "RCI Lab received KBSI infrastructure support for human-centered humanoid robotics." },
      { date: "2025.02", category: "Publication", title: "Hybrid A*-guided MPPI for rough-terrain navigation was accepted to Mathematics." },
      { date: "2025.02", category: "Service", title: "Prof. Sanghyun Kim was appointed an Associate Editor for IROS 2025." },
      { date: "2025.02", category: "Publication", title: "Eunae Kang and Jiho Hong presented vision-language navigation research at KROC 2025." },
      { date: "2025.02", category: "Publication", title: "A paper on sparse identification for online object-parameter estimation was accepted to JMST." },
      { date: "2025.01", category: "Service", title: "Prof. Sanghyun Kim joined the organizing committee for Humanoids 2025." },
      { date: "2025.01", category: "Grant", title: "RCI Lab began an autonomous path-generation software project with FunctionBay." },
    ],
  },
  {
    year: "2024",
    items: [
      { date: "2024.12", category: "Grant", title: "RCI Lab joined a KHNP project on radiation- and heat-resistant emergency-response robots." },
      { date: "2024.12", category: "Grant", title: "RCI Lab joined TIPA’s AI-robotics project for self-evolving next-generation material development." },
      { date: "2024.12", category: "Service", title: "Prof. Sanghyun Kim was appointed an adjunct researcher at AICT." },
      { date: "2024.12", category: "Award", title: "Bohyeong Pak received an Outstanding Poster Award at the Undergraduate Research Festival." },
      { date: "2024.12", category: "Publication", title: "A paper on MPPI-based whole-body control of a hybrid cable-driven robot was accepted to the Transactions of the KSME A." },
      { date: "2024.12", category: "Lab", title: "Minhyeong Kang, Leesai Park, Seulchan Lee, Jiho Hong, and Jaerak Son joined RCI Lab." },
      { date: "2024.12", category: "Lab", title: "Prof. Sanghyun Kim presented recent RCI Lab research at Sookmyung Women’s University." },
      { date: "2024.11", category: "Publication", title: "RCI Lab presented work on hybrid cable-driven robots and open-vocabulary semantic mapping at the KSME Annual Meeting." },
      { date: "2024.11", category: "Lab", title: "RCI Lab transferred ROS2 traversability-estimation and autonomous-navigation technology to PIT-IN." },
      { date: "2024.10", category: "Grant", title: "RCI Lab began an outdoor mobile-robot local path-planning project with HL Mando." },
      { date: "2024.10", category: "Publication", title: "Object-Aware Impedance Control was accepted to IEEE Transactions on Automation Science and Engineering." },
      { date: "2024.10", category: "Award", title: "Hakjun Kim received the Best Poster Award at ACMD 2024." },
      { date: "2024.10", category: "Lab", title: "Prof. Sanghyun Kim met with Prof. Sethu Vijayakumar and Prof. Jongwoo Park for research collaboration." },
      { date: "2024.09", category: "Lab", title: "Eunae Kang and Jiwon Yoon joined RCI Lab." },
      { date: "2024.09", category: "Service", title: "Prof. Sanghyun Kim was appointed an Associate Editor for ICRA 2025." },
      { date: "2024.08", category: "Grant", title: "RCI Lab joined an NRF Basic Research Laboratory on robot shared control for an aging society." },
      { date: "2024.08", category: "Grant", title: "RCI Lab joined an NRF STEAM project on humanoid avatar robots with multisensory interfaces." },
      { date: "2024.08", category: "Publication", title: "Two RCI Lab papers were presented at ACMD 2024." },
      { date: "2024.08", category: "Service", title: "Prof. Sanghyun Kim began serving as an Associate Editor for JMST." },
      { date: "2024.07", category: "Lab", title: "RCI Lab filed a patent on whole-body control of a hybrid cable-driven robot with a manipulator." },
      { date: "2024.07", category: "Publication", title: "Whole-body Control of Redundant Hybrid Cable-Driven Robot with Manipulator was accepted to Nonlinear Dynamics." },
      { date: "2024.07", category: "Lab", title: "RCI Lab registered lunar-rover autonomous-driving simulation software." },
      { date: "2024.06", category: "Grant", title: "RCI Lab developed traversability estimation for outdoor patrol robots with HL Mando." },
      { date: "2024.06", category: "Lab", title: "Prof. Sanghyun Kim visited Stanford University for research collaboration with Prof. Oussama Khatib." },
      { date: "2024.05", category: "Grant", title: "RCI Lab began an autonomous battery-swapping robot project supported by the Ministry of SMEs and Startups." },
      { date: "2024.05", category: "Grant", title: "RCI Lab began bridge-inspection robot control-system development with KICT." },
      { date: "2024.05", category: "Grant", title: "RCI Lab joined national projects in avatar robotics and robot digital-twin platforms." },
      { date: "2024.05", category: "Grant", title: "RCI Lab began industry projects on battery-swap AGVs, connector manipulation, and 2.5D navigation." },
      { date: "2024.04", category: "Publication", title: "Nonlinear Identification of Unknown Object Dynamics was presented at UR 2024." },
      { date: "2024.04", category: "Lab", title: "Leesai Park and Minhyeong Kang were selected for a six-week collaboration visit to IHMC." },
      { date: "2024.03", category: "Publication", title: "Online Multi-Contact Receding Horizon Planning via Value Function Approximation was accepted to IEEE Transactions on Robotics." },
      { date: "2024.02", category: "Lab", title: "RCI Lab transferred deep-reinforcement-learning-based humanoid gripper manipulation technology to Robros." },
      { date: "2024.02", category: "Lab", title: "RCI Lab filed a patent on a LiDAR-based mobile-robot docking system." },
      { date: "2024.01", category: "Publication", title: "A UWB localization filtering study was accepted to Sensors." },
    ],
  },
  {
    year: "2023",
    items: [
      { date: "2023.12", category: "Service", title: "Prof. Sanghyun Kim was appointed an Associate Editor for IROS 2024." },
      { date: "2023.12", category: "Publication", title: "A mobile-manipulator laser-welding automation paper was accepted to Applied Sciences." },
      { date: "2023.10", category: "Grant", title: "RCI Lab joined a national demonstration project for remanufactured-battery subscription services." },
      { date: "2023.10", category: "Grant", title: "RCI Lab received LINC 3.0 prototype support for a multi-object humanoid gripper." },
      { date: "2023.10", category: "Lab", title: "Suhwan Park joined RCI Lab as an integrated M.S./Ph.D. student." },
      { date: "2023.09", category: "Grant", title: "RCI Lab joined the NRF Planet-ex project for persistent autonomous exploration with heterogeneous robot teams." },
      { date: "2023.08", category: "Publication", title: "A dual-arm wiring-harness path-planning paper was accepted to IEEE Access." },
      { date: "2023.07", category: "Grant", title: "RCI Lab began developing topology-based work-sequence software for LNG cargo tanks with KIMM." },
      { date: "2023.07", category: "Lab", title: "RCI Lab went on a hiking trip to Cheonggyesan Mountain." },
      { date: "2023.06", category: "Grant", title: "RCI Lab received an NRF grant for robot–robot and human–robot collaborative transport." },
      { date: "2023.06", category: "Grant", title: "RCI Lab began KIMM projects on cable-system master control and HRI-based collision-safety software." },
      { date: "2023.05", category: "Award", title: "Weighted Hierarchical Quadratic Programming received the 2023 Intelligent Service Robotics Best Paper Award, second place." },
      { date: "2023.04", category: "Publication", title: "Motion Planning of Mobile Manipulator for Navigation Including Door Traversal was accepted to IEEE RA-L." },
      { date: "2023.04", category: "Publication", title: "Fusing Camera Perception and LiDAR Mapping for Improved Semantic Map was accepted to IAS 2023." },
      { date: "2023.04", category: "Lab", title: "RCI Lab transferred ROS2 autonomous-mobile-robot operation technology to Rotal." },
      { date: "2023.04", category: "Lab", title: "RCI Lab transferred ROS1 mecanum-wheel autonomous-navigation technology to Wonik Robotics." },
    ],
  },
];
